In [1]:
import numpy as np

In [12]:
patch_ir = np.random.uniform(low=0, high=255, size=16*16*32).reshape((16, 16, 32)).astype(np.uint8)

In [13]:
patch_ir

array([[[247, 165, 229, ...,  37,   5, 136],
        [ 64,  77, 128, ..., 162,  59, 209],
        [189,  76, 170, ..., 216, 220, 190],
        ...,
        [ 58,  38, 106, ..., 224, 170,   1],
        [110, 103,   6, ...,  46, 199, 121],
        [237,  84,  79, ...,  48,  81,  94]],

       [[ 87,  55, 106, ..., 245,  67,  57],
        [179, 133, 165, ...,  86,  85,  98],
        [ 74, 137,  75, ..., 105,   8, 208],
        ...,
        [ 36, 165, 240, ...,  72,  44,  26],
        [ 53, 112, 176, ..., 183,   7,  45],
        [139,  84,  46, ..., 247,  93, 227]],

       [[147,  19, 150, ..., 154,  83,   4],
        [ 19, 249,  97, ..., 245,  11,  98],
        [206, 194, 254, ...,  59,  89, 146],
        ...,
        [182, 109, 222, ..., 252, 190, 171],
        [217, 192,  34, ...,  17, 130,  22],
        [170, 195,  53, ...,  44,  22, 170]],

       ...,

       [[ 50, 208, 179, ..., 204, 234, 218],
        [133,  37, 169, ..., 201, 136, 252],
        [ 19,   7, 178, ..., 100,   7,  86

In [14]:
def max_pool(patch_ir, pool_size=8):

    height, width, nr_channels = patch_ir.shape

    patch_ir_reshaped = patch_ir.reshape(height // pool_size, pool_size,
                           width // pool_size, pool_size, nr_channels)
    patch_descr = patch_ir_reshaped.max(axis=1).max(axis=2)

    return patch_descr

In [16]:
def timing_max_pooling():
    for i in range(1000):
        max_pool(patch_ir)

In [17]:
%timeit timing_max_pooling

14.4 ns ± 0.0565 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [25]:
%timeit max_pool(patch_ir)

14.1 µs ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
patch_ir1 = np.random.uniform(low=0, high=255, size=16*16*32).reshape((16, 16, 32)).astype(np.uint8)
patch_ir2 = np.random.uniform(low=0, high=255, size=16*16*32).reshape((16, 16, 32)).astype(np.uint8)

patch_descr1 = max_pool(patch_ir1)
patch_descr2 = max_pool(patch_ir2)

In [20]:
%timeit np.sum(np.subtract(patch_descr1, patch_descr2, dtype=np.float32) ** 2)

6.93 µs ± 66.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
patch_rgb1 = np.random.uniform(low=0, high=255, size=16*16*3).reshape((16, 16, 3)).astype(np.uint8)
patch_rgb2 = np.random.uniform(low=0, high=255, size=16*16*3).reshape((16, 16, 3)).astype(np.uint8)

In [23]:
%timeit np.sum(np.subtract(patch_rgb1, patch_rgb2, dtype=np.float32) ** 2)

8.46 µs ± 72.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [27]:
def max_pool2(x):
    """Return maximum in groups of 2x2 for a N,h,w image"""
    N,h,w = x.shape
    return np.amax([x[(i>>1)&1::2,i&1::2,:] for i in range(4)],axis=0)

In [29]:
%timeit max_pool2(patch_ir)

17 µs ± 69.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [57]:
temp = np.arange(16)#.reshape(4,4)

In [58]:
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
for i in range(16):
#     print(temp[i&1::2])
    print(i&1)

0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1


In [43]:
temp[(i>>1)&1::2,i&1::2]

array([[ 1,  3],
       [ 9, 11]])